### ISSUE TITLE
conditional alerts

### ISSUE THREAD

**Issue by Dontorpedo** [KoalaFacade/Filament-Alertbox#12]
hello,

can you provide a example, how to make the alerts appear conditional?

thanks

**Comment by pemudakoding** [comment]
Hello @Dontorpedo 

you can play around with these method in form
![image](https://user-images.githubusercontent.com/62993054/230240256-0341b5c9-4357-45b1-b60a-db9bc7b0234f.png)

for widget you can play around with canView() method
