### ISSUE TITLE
Filament v3 - Upgrade

### ISSUE THREAD

**Issue by martin-arvisais** [KoalaFacade/Filament-Alertbox#16]
I would like to complete my upgrade to Filament v3. Do you plan to make this wonderful package of yours compatible with Filament v3?

**Comment by pemudakoding** [comment]
sure we planned for filament v3 support, will confirmed this issue to produce. 

Thanks @martin-arvisais

**Comment by pemudakoding** [comment]
Hi i've been released V3 support 

if any bugs appear kindly open new issue 

Many thanks,
Stiven
