### ISSUE TITLE
please provide a full documentation on how to use and customise this package

### ISSUE THREAD

**Issue by cobraprojects** [KoalaFacade/Filament-Alertbox#5]
the documentation is very poor

**Comment by pemudakoding** [comment]
> the documentation is very poor

Hi @cobraprojects you can find the docs here 
https://koalafacade.github.io/packages/filament-alertbox/

and what documentation you feel still lack? i will provide it for you, because  the docs base on our use case, Thanks.

**Comment by cobraprojects** [comment]
yeah I visited that link
but didn't find any code examples

**Comment by pemudakoding** [comment]
> yeah I visited that link but didn't find any code examples

we've 2 implementation widget and form 

https://koalafacade.github.io/packages/filament-alertbox/forms/
https://koalafacade.github.io/packages/filament-alertbox/widget/

are you still feel lack with those documentation? if yes i will make it with full example

**Comment by pemudakoding** [comment]
please let me know if clear

**Comment by cobraprojects** [comment]
yeah it's clear
thanks.

the link on the the title was a bit confusing, couldn't find it :)
I think it's better to provide a the link inside the content as well,

thanks again for your help

**Comment by pemudakoding** [comment]
alright Thanks we'll look our theme documentation and improve it as soon as possible, thanks for your input, I appreaciate it
