### ISSUE TITLE
CSS classes unknown

### ISSUE THREAD

**Issue by tpetry** [KoalaFacade/Filament-Alertbox#8]
The plugin uses a lot of css classes that are unknown, therefore no styling is applied. Classes like `mr-5` are clearly from tailwindcss but are not provided by filament or this plugin. But classes like `bg-danger-400` or `text-slate-50` seem to be completely custom.

**Comment by pemudakoding** [comment]
Hi @tpetry glad to know your feedbacks.

but let me help you. 
have you tried to do configuration like below and try build your assets again?
![image](https://user-images.githubusercontent.com/62993054/224313506-64837d21-9e39-4c6c-9c0c-f332ea510090.png)

if still not resolved i will provide solution for you as soon as possible 

Thanks..

**Comment by tpetry** [comment]
That doesn't work completely. If you add the code you also have to register the css file with filament:

```php
Filament::registerStyles([
   Vite::asset('resources/css/app.css'),
]);
```

That adds some styles. But still `bg-danger-400` or `text-slate-50` are not standard tailwind classes and therefore will not work.

--

Another problem with that approach is that my frontend styling is mixed with the backend styling. So when I change the colors in the frontend they are also changed in the backend (as you can't easily have two different tailwind configurations with vite). It would be best if the plugin would deliver a stylesheet that gets automatically included.

**Comment by pemudakoding** [comment]
Okie i got it, I would compile the style in our side or using filament base class instead. is it okay for you? 

if okay i would provide for you

**Comment by tpetry** [comment]
Sounds perfect!

**Comment by pemudakoding** [comment]
Hi @tpetry I fixed it by following filament base classes, the color will be a little dark than before, but the content still readable. if something still bothering you let me know, i will help you. 

if this issue is resolved please confirm i will close the issue
Thanks.

**Comment by tpetry** [comment]
Thanks, it is working better. But looking at the classes, some are still not included. For example the `p-5` is missing because filament hasn't exported all tailwind classes. I guess you have to do a custom tailwind build to include these.

**Comment by pemudakoding** [comment]
yeah i make bad decision before, i will fix it and align it with filament base class.

**Comment by pemudakoding** [comment]
Added additional classes can update the package again, and test

Thanks

**Comment by tpetry** [comment]
It is now working as expected! Thanks.

**Comment by tpetry** [comment]
![CleanShot 2023-03-10 at 15 37 05](https://user-images.githubusercontent.com/315686/224343486-c5e9dee7-c041-495a-bcbc-a46b9af9ba41.png)
Wouldn't it make sense if the font was always gray-50 on the colored background? dark grey on yellow looks strange.

**Comment by pemudakoding** [comment]
> ![CleanShot 2023-03-10 at 15 37 05](https://user-images.githubusercontent.com/315686/224343486-c5e9dee7-c041-495a-bcbc-a46b9af9ba41.png) Wouldn't it make sense if the font was always gray-50 on the colored background? dark grey on yellow looks strange.

what do you think? is the light color of text is more readable and comfortable for all colored background? 

if yes i will look at it and find a way out, and would mention you if done.

**Comment by pemudakoding** [comment]
> I tried it with whitish background (gray-50 like with danger) and in my opinion it looks a lot better. It's then also the same style for everything

Yeah i think whitish color is better for now, can update the package i update it to the white color.

**Comment by tpetry** [comment]
Looks good 👍

**Comment by pemudakoding** [comment]
glad to hear.  if in the future you have any feedback don't hesitate to raise an issue

Thanks for the feedback, it actually can help us to go further
